[command]
    [command."apps:create"]
        name = "apps:create"
        regex = '(\w+)'
        keys = ["name"]
        multiLine = false
        skipLines = 1

    [command."apps:list"]
        name = "apps:list"
        regex = '(\w+)'
        keys = ["name"]
        multiLine = true
        skipLines = 1

    [command."redis:list"]
        name = "redis:list"
        regex = '([\w\:\.-]+)'
        keys = ["name", "version", "status", "", "links"]
        multiLine = true
        skipLines = 1
